### ISSUE TITLE
`dist/esm/index.mjs` doesn't exist in distribution

### ISSUE THREAD

**Issue by chrisvariety** [CharlesStover/lazy-i18n#1]
Heya 👋 

Trying this package out and it looks like there's a small hitch in the package.json:

https://github.com/CharlesStover/lazy-i18n/blob/ff05bdc06c1b9a484b4e48ff43f77d5182bc4eea/package.json#L9

As far as I can tell, `dist/esm/index.mjs` doesn't actually exist in the distribution, but `dist/esm/index.js` does. Extract https://registry.npmjs.org/lazy-i18n/-/lazy-i18n-2.0.3.tgz to see yourself.

Changing the import to `import { I18nProvider } from 'lazy-i18n/dist/esm';` works as a workaround.

**Comment by CharlesStover** [comment]
Great find, thank you. Pushing `2.0.4` now, which points module to `dist/esm/index.js`.

**Comment by chrisvariety** [comment]
Thanks so much! 🙏

**Comment by chrisvariety** [comment]
Still struggling with this, but maybe I'm doing something wrong here? Using vite, which pre-bundles dependencies ( https://vitejs.dev/guide/dep-pre-bundling.html )

```
require() of /Users/chrismcc/workspace/ss/node_modules/lazy-i18n/dist/cjs/index.js from /Users/chrismcc/workspace/ss/node_modules/vite/dist/node/chunks/dep-2c03f3f9.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/chrismcc/workspace/ss/node_modules/lazy-i18n/package.json.
```

**Comment by CharlesStover** [comment]
That makes sense. Interesting that I've never encountered it with Webpack or Rollup.

I've pushed 2.0.6 to address this, but [Travis CI seems to be hanging atm](https://travis-ci.com/github/CharlesStover/lazy-i18n/builds/224826597). It usually will have finished deploying by now. I'll let it go on, presuming temporary server troubles on their end, but let me know if nothing publishes, and I'll force a rebuild. 🙂

**Comment by chrisvariety** [comment]
`2.0.9` is working a-okay in my vite app. thanks much!
